# Generated by Django 4.0.1 on 2022-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_question_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_name',
            field=models.TextField(max_length=4096),
        ),
    ]
