# Generated by Django 4.0.1 on 2022-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='image/avatars/user.png', upload_to='image/avatars/'),
        ),
    ]
